### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by eliovir** [jdavis/rust-design-patterns#4]
Hi,

At https://github.com/jdavis/rust-design-patterns/blob/master/patterns/adapter.rs#L72,
is "Turing off the Dragon." a word play or it must be "Turning off the Dragon."  ?

**Comment by jdavis** [comment]
Haha. I wish I had been clever enough to make a CompSci pun. But alas, you are correct. It is a typo. Thanks for pointing it out!

**Comment by eliovir** [comment]
Thanks for your project!

**Comment by jdavis** [comment]
No problem. Hopefully I'll be able to add some more design patterns soon. I've been quite busy.
